services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: academic_chatbot_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/group_uploads:/app/group_uploads
      - ./backend/vectorstore:/app/vectorstore
      - ./backend/.env:/app/.env  
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: academic_chatbot_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  group-uploads:
